[experimental] test libc++ built by clang; link tests with compiler-rt
Trying to make libc++ work with clang
1. Turns out libc++ needs some features exists in clang to work.  Previously
   we compile all STL in NDK with default compiler which is gcc 4.6.
   In this experiment, we switch to clang3.3 (exists since r9)

   ./build/tools/build-cxx-stl.sh --stl=libc++ --ndk-dir=$NDK --llvm-version=3.3

2. Clang needs compiler-rt for helpers used by code expanded
   from intrinsics (eg. __atomic_exchange).  This patch add -lcompiler_rt*
   for linker.

To test:
  cd $NDK
  ./build/tools/make-standalone-toolchain.sh --platform=android-9 --llvm-version=3.3 \
    --install-dir=/path/to/ndk/standalone/ndk-api9-arm --arch=arm

  cd $NDK/sources/cxx-stl/llvm-libc++/libcxx/test
  PATH=/path/to/ndk/standalone/ndk-api9-arm:$PATH \
    ./testit_android --abi=armeabi-v7a --cxx=arm-linux-androideabi-clang++

Fail count of section/test drop from 208/682 to 91/262 fails remain (out of 1071/4418)

Change-Id: I213448129f82b70542fca4e4603fb50e023a1f9e

diff --git a/sources/cxx-stl/llvm-libc++/libcxx/test/testit_android b/sources/cxx-stl/llvm-libc++/libcxx/test/testit_android
--- a/sources/cxx-stl/llvm-libc++/libcxx/test/testit_android
+++ b/sources/cxx-stl/llvm-libc++/libcxx/test/testit_android
@@ -170,6 +170,16 @@ for LIB in libc++_static.a libc++_shared.so; do
   fi
 done
 
+LIBCOMPILER_RT_LIBS=$(cd "$LIBCXX_ROOT"/../../../android/compiler-rt && pwd)/libs/$TARGET_ABI
+for LIB in libcompiler_rt_static.a libcompiler_rt_shared.so; do
+  if [ ! -f "$LIBCOMPILER_RT_LIBS/$LIB" ]; then
+    echo "ERROR: Missing prebuilt library: $LIBCOMPILER_RT_LIBS/$LIB"
+    echo "Please run: build/tools/build-compiler-rt.sh --ndk-dir=$NDK \
+--src-dir=/tmp/ndk-$USER/src/llvm-3.3/compiler-rt --llvm-version=3.3"
+    exit 1
+  fi
+done
+
 # Check or detect C++ toolchain.
 TOOLCHAIN_CFLAGS=
 TOOLCHAIN_LDFLAGS=
@@ -222,6 +232,8 @@ if [ -z "$SOURCE_LIB" ]
 then
        SOURCE_LIB="-L$LIBCXX_LIBS"
 fi
+SOURCE_LIB="$SOURCE_LIB -L$LIBCOMPILER_RT_LIBS"
+
 if [ -z "$ADB" ]
 then
        ADB=adb
@@ -229,14 +241,19 @@ fi
 
 if [ "$DO_STATIC" ]; then
   # Statically link to ensure the executable can be run easily through ADB
-  LIBS=-lc++_static
+  LIBS="-lc++_static -lcompiler_rt_static"
 else
   run2 $ADB push $LIBCXX_LIBS/libc++_shared.so /data/local/tmp 2>/dev/null
   if [ $? != 0 ]; then
     echo "ERROR: Can't push shared libc++ to target device!"
     exit 1
   fi
-  LIBS=-lc++_shared
+  run2 $ADB push $LIBCOMPILER_RT_LIBS/libcompiler_rt_shared.so /data/local/tmp 2>/dev/null
+  if [ $? != 0 ]; then
+    echo "ERROR: Can't push shared libcompiler_rt to target device!"
+    exit 1
+  fi
+  LIBS="-lc++_shared -lcompiler_rt_shared"
 fi
 
 case $TRIPLE in
