Bail out when NDK installation path contains space
Check to ensure NDK isn't installed in path
containing space.  Many NDK scripts aren't ready to handle
path with space yet.

Change-Id: I1a76a9ff7bb84fd9a5c27f73e17b753c858070e7

diff --git a/ndk-build b/ndk-build
--- a/ndk-build
+++ b/ndk-build
@@ -40,6 +40,14 @@
 PROGDIR=`dirname $0`
 PROGDIR=`cd $PROGDIR && pwd`
 
+# Check if absolute NDK path contain space
+#
+case $PROGDIR in
+    *\ *) echo "ERROR: NDK path cannot contain space"
+          exit 1
+        ;;
+esac
+
 # If NDK_LOG is set to 1 or true in the environment, or the command-line
 # then enable log messages below
 if [ -z "$NDK_LOG" ]; then
